version: '3.4'
volumes: 
  pub-base:
services:
  godartpub:
    image: godartpub
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - pub-base:/data
    network_mode: host
